export interface BuiltinCollectionDef {
  id: string;
  name: string;
  icon: string;
  description: string;
  problemIds: string[];
}

export const BUILTIN_COLLECTIONS: BuiltinCollectionDef[] = [
  {
    id: "blind-75",
    name: "Blind 75",
    icon: "🎯",
    description: "The 75 most frequently asked LeetCode problems across top tech companies",
    problemIds: [
      "two-sum", "longest-substring-without-repeating-characters",
      "longest-palindromic-substring", "container-with-most-water",
      "3sum", "remove-nth-node-from-end-of-list",
      "valid-parentheses", "merge-two-sorted-lists",
      "merge-k-sorted-lists", "maximum-subarray",
      "best-time-to-buy-and-sell-stock", "product-of-array-except-self",
      "maximum-product-subarray", "find-minimum-in-rotated-sorted-array",
      "search-in-rotated-sorted-array", "combination-sum",
      "word-search", "number-of-islands",
      "clone-graph", "course-schedule",
      "longest-increasing-subsequence", "longest-common-subsequence",
      "word-break", "combination-sum-iv",
      "house-robber", "house-robber-ii",
      "decode-ways", "unique-paths",
      "jump-game", "climbing-stairs",
      "coin-change", "palindromic-substrings",
      "serialize-and-deserialize-binary-tree", "binary-tree-maximum-path-sum",
      "maximum-depth-of-binary-tree", "same-tree",
      "invert-binary-tree", "binary-tree-level-order-traversal",
      "subtree-of-another-tree", "kth-smallest-element-in-a-bst",
      "lowest-common-ancestor-of-a-binary-search-tree", "validate-binary-search-tree",
      "insert-interval", "merge-intervals",
      "non-overlapping-intervals", "minimum-window-substring",
      "longest-repeating-character-replacement", "group-anagrams",
      "valid-anagram", "top-k-frequent-elements",
      "accounts-merge", "sort-colors",
      "implement-trie-prefix-tree", "median-of-two-sorted-arrays",
      "longest-consecutive-sequence", "missing-number",
      "set-matrix-zeroes", "rotate-image",
      "spiral-matrix", "reverse-linked-list",
      "palindrome-linked-list", "linked-list-cycle",
      "reorder-list", "sort-list",
      "find-the-duplicate-number", "task-scheduler",
    ],
  },
  {
    id: "neetcode-150",
    name: "NeetCode 150",
    icon: "🔄",
    description: "Curated list of 150 problems covering all major patterns for coding interviews",
    problemIds: [
      "contains-duplicate", "valid-anagram", "two-sum",
      "group-anagrams", "top-k-frequent-elements",
      "product-of-array-except-self", "longest-consecutive-sequence",
      "valid-palindrome", "longest-palindromic-substring",
      "palindromic-substrings", "valid-parentheses",
      "minimum-window-substring", "longest-repeating-character-replacement",
      "longest-substring-without-repeating-characters", "valid-sudoku",
      "best-time-to-buy-and-sell-stock", "maximum-subarray",
      "maximum-product-subarray", "find-minimum-in-rotated-sorted-array",
      "search-in-rotated-sorted-array", "3sum",
      "container-with-most-water", "trapping-rain-water",
      "reverse-linked-list", "merge-two-sorted-lists",
      "reorder-list", "remove-nth-node-from-end-of-list",
      "linked-list-cycle", "merge-k-sorted-lists",
      "palindrome-linked-list", "lru-cache",
      "implement-trie-prefix-tree", "binary-search",
      "search-a-2d-matrix", "koko-eating-bananas",
      "median-of-two-sorted-arrays", "invert-binary-tree",
      "maximum-depth-of-binary-tree", "same-tree",
      "subtree-of-another-tree", "binary-tree-level-order-traversal",
      "binary-tree-maximum-path-sum", "serialize-and-deserialize-binary-tree",
      "validate-binary-search-tree", "kth-smallest-element-in-a-bst",
      "number-of-islands", "clone-graph",
      "max-area-of-island", "course-schedule",
      "course-schedule-ii", "climbing-stairs",
      "coin-change", "longest-increasing-subsequence",
      "longest-common-subsequence", "word-break",
      "combination-sum-iv", "house-robber",
      "house-robber-ii", "decode-ways",
      "unique-paths", "jump-game",
      "combination-sum", "word-search",
      "subsets", "permutations",
      "letter-combinations-of-a-phone-number", "insert-interval",
      "merge-intervals", "non-overlapping-intervals",
      "missing-number", "find-the-duplicate-number",
      "sort-colors", "set-matrix-zeroes",
      "rotate-image", "spiral-matrix",
      "accounts-merge", "sort-list",
      "task-scheduler", "sliding-window-maximum",
    ],
  },
  {
    id: "leetcode-75",
    name: "LeetCode 75",
    icon: "⚡",
    description: "The official LeetCode 75 study plan for interview preparation",
    problemIds: [
      "merge-strings-alternately", "greatest-common-divisor-of-strings",
      "kids-with-the-greatest-number-of-candies", "can-place-flowers",
      "reverse-vowels-of-a-string", "reverse-words-in-a-string",
      "product-of-array-except-self", "increasing-triplet-subsequence",
      "string-compression", "move-zeroes",
      "is-subsequence", "container-with-most-water",
      "maximum-number-of-vowels-in-a-substring-of-given-length",
      "maximum-average-subarray-i", "find-pivot-index",
      "unique-number-of-occurrences", "remove-stars-from-a-string",
      "asteroid-collision", "decode-string",
      "delete-the-middle-node-of-a-linked-list", "odd-even-linked-list",
      "reverse-linked-list", "maximum-twin-sum-of-a-linked-list",
      "maximum-depth-of-binary-tree", "leaf-similar-trees",
      "count-good-nodes-in-binary-tree", "path-sum-iii",
      "longest-zigzag-path-in-a-binary-tree",
      "lowest-common-ancestor-of-a-binary-tree",
      "binary-tree-right-side-view", "maximum-level-sum-of-a-binary-tree",
      "search-in-a-binary-search-tree", "delete-node-in-a-bst",
      "keys-and-rooms", "number-of-provinces",
      "rotting-oranges", "kth-largest-element-in-an-array",
      "guess-number-higher-or-lower", "find-peak-element",
      "letter-combinations-of-a-phone-number", "generate-parentheses",
      "unique-paths", "longest-common-subsequence",
      "best-time-to-buy-and-sell-stock-with-transaction-fee",
      "edit-distance", "min-cost-climbing-stairs",
      "house-robber", "n-th-tribonacci-number",
      "single-number", "number-of-1-bits",
      "counting-bits", "implement-trie-prefix-tree",
      "non-overlapping-intervals", "daily-temperatures",
    ],
  },
];
